from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from datetime import datetime, timezone
from backend.app.database import get_db
from backend.app.storage.repository import LifedRepository

router = APIRouter(prefix="/api/dashboard", tags=["Dashboard"])

@router.get("")
def get_dashboard_summary(db: Session = Depends(get_db)):
    repo = LifedRepository(db)
    
    tasks = repo.get_tasks()
    projects = repo.get_projects()
    goals = repo.get_goals()
    
    # Priority sorting (urgent -> high -> medium -> low)
    priority_weights = {"urgent": 4, "high": 3, "medium": 2, "low": 1}
    pending_tasks = [t for t in tasks if t.status != "completed"]
    sorted_pending = sorted(
        pending_tasks,
        key=lambda x: priority_weights.get(x.priority.lower(), 0),
        reverse=True
    )
    
    top_priorities = []
    for t in sorted_pending[:5]:
        top_priorities.append({
            "id": t.id,
            "title": t.title,
            "priority": t.priority,
            "estimated_duration": t.estimated_duration,
            "deadline": t.deadline,
            "status": t.status,
            "project_id": t.project_id
        })
        
    completed_count = sum(1 for t in tasks if t.status == "completed")
    
    # Dynamic greeting
    hour = datetime.now().hour
    if hour < 12:
        greeting = "GOOD MORNING"
    elif hour < 17:
        greeting = "GOOD AFTERNOON"
    else:
        greeting = "GOOD EVENING"
        
    # AI Insight (defaults to contextual observation if not generated by LLM yet)
    ai_insight = "Prioritize high-impact goal deliverables today before addressing operational backlog items."
    if len(pending_tasks) > 0 and any(t.priority in ["urgent", "high"] for t in pending_tasks):
        ai_insight = "You have high-priority tasks pending. Allocate focus blocks early to maintain project velocity."

    return {
        "greeting": greeting,
        "date": datetime.now().strftime("%A, %B %d"),
        "top_priorities": top_priorities,
        "ai_insight": ai_insight,
        "counts": {
            "total_tasks": len(tasks),
            "pending_tasks": len(pending_tasks),
            "completed_tasks": completed_count,
            "active_projects": len([p for p in projects if p.status == "active"]),
            "active_goals": len([g for g in goals if g.status == "active"]),
        },
        "goals_summary": [
            {"id": g.id, "title": g.title, "progress": g.progress, "status": g.status}
            for g in goals[:4]
        ],
        "active_projects": [
            {"id": p.id, "title": p.title, "status": p.status}
            for p in projects[:4]
        ]
    }
